DEFAULT_TIMEOUT = 30.0
DEFAULT_BASE_URL = "https://api.bigchange.com"
DEFAULT_API_VERSION = "v1"
RETRYABLE_STATUS_CODES = {429, 500, 502, 503, 504}
IDEMPOTENT_METHODS = {"GET", "HEAD", "PUT", "DELETE", "PATCH"}